name: "csvlinter"
description: "Lint your delimited files including comma (csv), tab separated etc using csvlint"
author: "kcheriyath"
inputs:
  file_list: # id of input
    description: "(optional) when defined, linter will use this file list only and find* parameters are ignored. Use as a static list or with jitterbit/get-changed-files to check only new files."
    required: false
  find_path: # id of input
    description: "(optional) when defined, find command is used to search for csv files in the path, relative to project root. defaults to ."
    required: false
    default: "."
  find_pattern: # id of input
    description: "(optional) File name or pattern to find. Defaults to *.csv"
    required: false
    default: "*.csv"
  extra_params: # id of input
    description: "(optional) extra parameters passed to the csvlint command. see usage in README."
    required: false
    default: "--lazyquotes"
  fail_on_error: # id of input
    description: "(optional) Should action fail on error"
    required: false
    default: "true"    

branding:
  icon: "file-plus"
  color: "green"
runs:
  using: "docker"
  image: "Dockerfile"
