# This is a basic workflow to help you get started with Actions

name: on_PR

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: csv lint
    steps:
    - uses: actions/checkout@v3
    - name: Run csv-lint
      uses: kcheriyath/csvlinter@main
      with:
        find_pattern: "*.csv"
        find_path: "examples"
        extra_params: "--lazyquotes"
